"""Add provenance fields to ImportRun

Revision ID: 7ddf4996c868
Revises: a63fd328dcf6
Create Date: 2026-02-05 00:55:16.341807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddf4996c868'
down_revision: Union[str, Sequence[str], None] = 'a63fd328dcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_runs', sa.Column('sha256_hash', sa.String(length=64), nullable=True))
    op.add_column('import_runs', sa.Column('parser_version', sa.String(length=50), nullable=True))
    op.add_column('import_runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('import_runs', 'duration_ms')
    op.drop_column('import_runs', 'parser_version')
    op.drop_column('import_runs', 'sha256_hash')
    # ### end Alembic commands ###
