"""add event ownership

Revision ID: 8c8851f64d1d
Revises: 290a4b3ac4a5
Create Date: 2026-03-17 19:23:58.704212

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c8851f64d1d'
down_revision: Union[str, Sequence[str], None] = '290a4b3ac4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'created_by_user_id')
    # ### end Alembic commands ###
