"""Add novel data integration tables

Revision ID: a63fd328dcf6
Revises: 5b216861ccd7
Create Date: 2026-02-04 00:54:06.792294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63fd328dcf6'
down_revision: Union[str, Sequence[str], None] = '5b216861ccd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Add columns directly
    op.add_column('events', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('source_record_id', sa.String(length=100), nullable=True))
    # SQLite needs server_default for non-nullable new columns
    op.add_column('events', sa.Column('is_seeded', sa.Boolean(), nullable=False, server_default='0'))
    
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_events_data_sources', 'data_sources', ['source_id'], ['id'])

    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_username'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_data_sources', type_='foreignkey')
        batch_op.drop_column('is_seeded')
        batch_op.drop_column('source_record_id')
        batch_op.drop_column('source_id')
        
    op.drop_table('import_runs')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
